# Generated by Django 3.1.13 on 2021-09-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings_adress', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addressnew',
        ),
        migrations.RenameModel(
            old_name='Letting',
            new_name='Lettingnew',
        ),
    ]
