# Generated by Django 3.1.13 on 2021-09-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings_adress', '0002_auto_20210929_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addressnew',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Lettingnew',
            new_name='Letting',
        ),
    ]
