# Generated by Django 3.1.13 on 2021-09-29 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oc_lettings_site', '0003_addressold_lettingold_profileold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addressold',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Lettingold',
            new_name='Letting',
        ),
        migrations.RenameModel(
            old_name='Profileold',
            new_name='Profile',
        ),
    ]
